version: "3"

services:
  arkenstone-dev-postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: arkenstone
      POSTGRES_USER: arkenstone
      POSTGRES_PASSWORD: arkenstone
    ports:
      - "127.0.0.1:45432:5432"
    networks:
      - arkenstone-dev

  arkenstone-dev-phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=arkenstone
      - PHP_PG_ADMIN_SERVER_HOST=arkenstone-dev-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=arkenstone
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_OWNED_ONLY=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_SHOW_OIDS=true
    ports:
      - "127.0.0.1:48081:80"
    depends_on:
      - arkenstone-dev-postgres
    networks:
      - arkenstone-dev

networks:
  arkenstone-dev:
