name: CI

on: [push]

jobs:
  build-service:
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "debug"
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v1

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Cargo Check
        run: |
          cd service
          cargo check

      - name: Cargo Clippy
        run: |
          cd service
          cargo clippy

      - name: Cargo Test
        run: |
          cd service
          cargo test --features docker_tests

  build-service-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get the git tag
        run: |
          echo ::set-env name=GIT_TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/.*\///g")

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: docker.pkg.github.com
          username: "publisher"
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: "${{ format('{0}/arkenstone-service', github.repository) }}"
          image_tag: "${{ env.GIT_TAG }}"
          push_git_tag: true
          context: service
